# docker-compose -f ./docker/docker-compose-dev.yaml up --build -d
# docker-compose -f ./docker/docker-compose-dev.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-facemap-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-facemap/docker/Dockerfile.dev
    env_file: .env
    image: workflow-facemap-dev:0.1.0a2
    container_name: workflow-facemap-dev
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - FACEMAP_ROOT_DATA_DIR=/main/facemap_inbox/
      - FACEMAP_PROCESSED_DATA_DIR=/main/facemap_outbox/
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-facemap:/main/element-facemap
      - ..:/main/workflow-facemap
    depends_on:
      db:
        condition: service_healthy
networks:
  main: